mod 'apt',
  :git => 'git@github.com:example42/puppet-apt.git'

mod 'concat',
  :git => 'https://github.com/puppetlabs/puppetlabs-concat.git'

mod 'rundeck',
  :git => 'git@github.com:gehel/puppet-rundeck.git'

mod 'stdlib',
  :git => 'git@github.com:puppetlabs/puppetlabs-stdlib.git'

mod 'puppi',
  :git => 'git@github.com:example42/puppi.git'

