# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "debian-7.3-puppet"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/debian-73-x64-virtualbox-puppet.box"

  config.vm.define "mysql" do |mysql|
    mysql.vm.hostname = "mysql"
    mysql.vm.network "private_network", ip: "192.168.50.10"
  end
  config.vm.define "graphite1" do |graphite1|
    graphite1.vm.hostname = "graphite1"
    graphite1.vm.network "private_network", ip: "192.168.50.21"
  end
  config.vm.define "graphite2" do |graphite2|
    graphite2.vm.hostname = "graphite2"
    graphite2.vm.network "private_network", ip: "192.168.50.22"
  end
  config.vm.define "memcached1" do |memcached1|
    memcached1.vm.hostname = "memcached1"
    memcached1.vm.network "private_network", ip: "192.168.50.31"
  end
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.hostname = "haproxy"
    haproxy.vm.network "private_network", ip: "192.168.50.200"
  end

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = [ "modules", "dist" ]
    puppet.manifest_file = "site.pp"
  end

end

